import type { UnifiedDatasetRow } from "./build-unified-dataset";

export const EXPECTED_HEADER_ORDER = [
  "كود القطعة",
  "كود الشخص",
  "رقم الحيازة",
  "كود الجمعية الزراعية",
  "اسم الجمعية",
  "نوع الجمعية",
  "تصنيف الجمعيات الزراعية",
  "اسم المالك من الحصر الميداني",
  "الرقم القومي للمالك",
  "اسم الحائز من الحصر الميداني",
  "الرقم القومي للحائز",
  "رقم القطعة",
  "المساحة الكلية للحيازة",
  "فدان",
  "قيراط",
  "سهم",
  "كود الحوض",
  "اسم الحوض",
  "نوع التربة",
  "نوع الاستخدام",
  "نوع المحصول",
  "مراحل النمو",
  "اسم الحائز من كارت الفلاح",
  "اسم المالك من كارت الفلاح",
  "ملاحظات من فريق العمل الميداني",
];

export const sampleRow: UnifiedDatasetRow = {
  id: "h-uuid-001",
  cityId: "c-uuid-001",
  personId: "p-uuid-001",
  cityName: "جمعية الشرقية",
  associationType: "agricultural_reform",
  associationSubtype: "نوع فرعي",
  classification: "استصلاح",
  shortCode: "SHQ",
  holderName: "محمد علي",
  nationalId: "12345678901234",
  ownerName: "أحمد محمد",
  holdingIdNumber: "5423",
  landNumber: "100",
  totalSqm: 5000,
  feddan: 1,
  qirat: 2,
  sahm: 3,
  basinCode: "B001",
  basinName: "حوض الشرقية",
  borderEast: "شارع النيل",
  borderWest: "شارع الجيش",
  borderSouth: "طريق القاهرة",
  borderNorth: "طريق الإسكندرية",
  soilType: "رملي",
  usageType: "زراعة",
  cropType: "قمح",
  growthStages: null,
  holderNameFarmerCard: null,
  ownerNameFarmerCard: null,
  notes: "بعض الملاحظات",
};

export const emptyRow: UnifiedDatasetRow = {
  id: "test",
  cityId: "test",
  personId: null,
  cityName: null,
  associationType: null,
  associationSubtype: null,
  classification: null,
  shortCode: null,
  holderName: null,
  nationalId: null,
  ownerName: null,
  holdingIdNumber: null,
  landNumber: null,
  totalSqm: null,
  feddan: 0,
  qirat: 0,
  sahm: 0,
  basinCode: null,
  basinName: null,
  borderEast: null,
  borderWest: null,
  borderSouth: null,
  borderNorth: null,
  soilType: null,
  usageType: null,
  cropType: null,
  growthStages: null,
  holderNameFarmerCard: null,
  ownerNameFarmerCard: null,
  notes: null,
};
